### ISSUE TITLE
Better base stack

### ISSUE THREAD

**Issue by gngdb** [edinburghlivinglab/livinglab-hubserver#8]
Just found these base stacks, which may be better than the current one: https://github.com/jupyter/docker-stacks

**Comment by ewan-klein** [comment]
You mean e.g. the scipy-notebook?

**Comment by gngdb** [comment]
Looking into this, their actually not as good, because they haven't built scipy and numpy against OpenBLAS, which is what we have in our current one. So, ours [should be faster](http://osdf.github.io/blog/numpyscipy-with-openblas-for-ubuntu-1204-second-try.html).
